### ISSUE TITLE
Mobs are not stacking

### ISSUE THREAD

**Issue by JPVortex225** [Nathat23/StackMob-2#100]
**Describe the bug**
I just downloaded StackMobs for 1.13.1, but mobs are not stacking.

**To Reproduce**
Spawning mobs will not stack mobs.

**Expected behavior**
Mobs stacking 

**Screenshots/Videos**
https://user-images.githubusercontent.com/41598891/44951471-e649e380-ae32-11e8-8909-1a7d17ffa2d0.png

**Bukkit/Spigot AND StackMob version:**
My StackMob version is: 2.4.0, Spigot version: 1.13.1-R0.1-SNAPSHOT

Thank you for reading!

**Comment by JPVortex225** [comment]
Spawn eggs. So I don’t know, do they have to be naturally spawned to stack?

**Comment by JPVortex225** [comment]
I was using spawn eggs to test it out

**Comment by Nathat23** [comment]
Are you using the default config.yml or a custom one?

**Comment by JPVortex225** [comment]
The default I have used previous versions in the past so I made sure to delete the StackMob to stop any errors

**Comment by Nathat23** [comment]
Are there any errors in console?

**Comment by JPVortex225** [comment]
No I checked that last night before contacting you and there was nothing

**Comment by Nathat23** [comment]
Have you tried spawning them in a 2x2 boxed area?

**Comment by JPVortex225** [comment]
No I will try that now though, I’m booting up my pc

**Comment by JPVortex225** [comment]
I cannot test it at this time, my server, as it’s node is out right now for some reason. I will get back to you as soon as possible

**Comment by JPVortex225** [comment]
My server just came back up, and I tested it in a 2x2 area. They are still not stacking at all...

**Comment by Nathat23** [comment]
you need at least 5 in an area for the mobs to stack.

**Comment by JPVortex225** [comment]
I spawned over 20 and they won't stack at all

**Comment by JPVortex225** [comment]
Alright I'll tell you if I figure anything, thanks for doing what you can to help. :)

**Comment by Nathat23** [comment]
Has this been solved? @JPVortex225 
If not, what does your config look like?

**Comment by Nathat23** [comment]
Closed because of no response.
