### ISSUE TITLE
Stackmob (console error)

### ISSUE THREAD

**Issue by johnsoncui02** [Nathat23/StackMob-2#105]
Server Version: 1.12.2
Stackmob Version: 2.2.14
MinimaturePets version: 2.0.0

Issue: unsure of but it's a console error.
https://pastebin.com/cJg5rxbV

**Comment by johnsoncui02** [comment]
confirmed that we're not updating stackmobs to be compatible?

**Comment by Nathat23** [comment]
well there isn't any documentation and in the update log it states that the api was removed, so I can't really do much.

**Comment by Nathat23** [comment]
a version checker has been added in the latest version for miniaturepets.
