### ISSUE TITLE
StackMob-2.4.1 / Paper 231 (1.13.1) - load problem

### ISSUE THREAD

**Issue by minecraft7net** [Nathat23/StackMob-2#106]
Hi - i saw an error when latest version is loaded on paper 231

StackMob-2.4.1

[13:33:43] [Server thread/INFO]: This server is running Paper version git-Paper-231 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

error:
https://pastebin.com/Zyj5k5LC

**Comment by Nathat23** [comment]
Delete the lang.yml file and restart the server.

**Comment by Nathat23** [comment]
Reset the config.yml aswell.

**Comment by minecraft7net** [comment]
yes thanks after config restet - no errors - thanks ! for updates :) and help
