### ISSUE TITLE
Certain mob stacks all die when attacked.

### ISSUE THREAD

**Issue by drzant12** [Nathat23/StackMob-2#107]
**Describe the bug**
While doing some testing, I realized that some mobs, like cows, will all die but 1 when killing. I can have a stack of like 300 and hit them a couple of times, then they all die and leave just 1 cow. The drops wont multiple either. 
I wish to be able to only have 1 or 2 cows die at a time. 

I tested on squid and phantoms also. They work fine. only 1 die at a time.

**To Reproduce**
stacking certain mobs together.

**Expected behavior**
I expected only 1 or 2 cows/sheep/pigs per stack to die when attacked instead of all -1

**Screenshots/Videos**

**Bukkit/Spigot AND StackMob version:**
spigot 1.13  SM 2.4.1

**Additional context**

**Comment by Nathat23** [comment]
Does disabling 'multiply-damage-received' change anything?

**Comment by Nathat23** [comment]
@drzant12 Please respond.

**Comment by Nathat23** [comment]
Closed because of no response.
