### ISSUE TITLE
error

### ISSUE THREAD

**Issue by LoToRTv** [Nathat23/StackMob-2#108]
Hello how fix error ? https://hastebin.com/numekuhepi.bash

**Comment by Nathat23** [comment]
that link is invalid

**Comment by LoToRTv** [comment]
Sorry 

>[18:53:52 WARN]: [StackMob] Task #75 for StackMob v2.4.1 generated an exception
>java.lang.IllegalArgumentException: Career id must be greater than 0
>        at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[spigot.jar:git-Spigot-6b015b4-a4bdecf]
>        at org.bukkit.craftbukkit.v1_13_R2.entity.CraftVillager.getCareer(CraftVillager.java:134) ~[spigot.jar:git-Spigot-6b015b4-a4bdecf]
>        at org.bukkit.craftbukkit.v1_13_R2.entity.CraftVillager.getCareer(CraftVillager.java:54) ~[spigot.jar:git-Spigot-6b015b4-a4bdecf]
>        at uk.antiperson.stackmob.tools.EntityTools.notMatching(EntityTools.java:70) ~[?:?]
>        at uk.antiperson.stackmob.tools.EntityTools.notEnoughNearby(EntityTools.java:293) ~[?:?]
>        at uk.antiperson.stackmob.listeners.entity.SpawnEvent$1.run(SpawnEvent.java:94) ~[?:?]
>        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot.jar:git-Spigot-6b015b4-a4bdecf]
>        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot.jar:git-Spigot-6b015b4-a4bdecf]
>        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigot.jar:git-Spigot-6b015b4-a4bdecf]
>        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411) [spigot.jar:git-Spigot-6b015b4-a4bdecf]
>        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot.jar:git-Spigot-6b015b4-a4bdecf]
>        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot.jar:git-Spigot-6b015b4-a4bdecf]
