### ISSUE TITLE
Named mobs are stacking.

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-2#111]
Currently using the latest StackMob from legacy branch.

Splitting a mob out from a stack with a name tag works fine, and that mob never stacks again.
However, upon a server restart, the named mob will stack once more into nearby stacks.

Please save named mobs into the cache and not just the memory (which is what I'm assuming is happening now, just memory saving).

**Comment by eightbitx** [comment]
This is still an issue.

**Comment by Nathat23** [comment]
> This is still an issue.

Could you elaborate further? I just tested and the split entity doesn't restack.

**Comment by Nathat23** [comment]
> > This is still an issue.
> 
> Could you elaborate further? I just tested and the split entity doesn't restack.

Nevermind, it does after a couple restarts.

**Comment by Nathat23** [comment]
Fixed.
