### ISSUE TITLE
Chickens not breeding properly

### ISSUE THREAD

**Issue by Terasat** [Nathat23/StackMob-2#112]
**Describe the bug**
Chickens stack, but when feed to breed they do not split the stack. 

**Expected behavior**
Chickens split to breed.

**Bukkit/Spigot AND StackMob version:**
Spigot 1.13

**Comment by Nathat23** [comment]
This works fine in my testing. What are you doing to breed the chickens?

**Comment by Nathat23** [comment]
@Terasat

**Comment by Terasat** [comment]
After getting your response I continued to test and found it was only one group of chickens that had this nature, I created another group of chickens and it worked fine. I went back and it refused to breed that group of chickens. The hearts would go above the head but not split. When I killed that group, only one set of items dropped from it. I have yet to reproduce the bug. 

If I can find a way to reproduce it, I will let you know, but as of now, it may have just been a server hiccup. 

Thank you for all the hard work.

**Comment by Nathat23** [comment]
Okay then, closing this.
