### ISSUE TITLE
Lead dupe.

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-2#121]
- find a stacked mob (eg chicken or cow)
- attach a lead to the stacked mob
- walk to a single mob of same type, or to a stack that has less stacked than yours
- when the mob(s) nearby stack to your stacked mob (the one you have a lead attached to), they will join your stacked mob, dropping an extra lead on the ground.

**Comment by Nathat23** [comment]
Fixed in latest commit.
