### ISSUE TITLE
Art

### ISSUE THREAD

**Issue by WizzleBear** [Nathat23/StackMob-2#125]
I seriously couldn't get you to see this so this is my last resort.
![Image](https://proxy.spigotmc.org/77dfa4d8b880e52b001827d651b4d847f7af522a?url=https%3A%2F%2Fi.imgur.com%2FfH90miR.png)
![Image](https://proxy.spigotmc.org/4a27690d882eab6794b63a4e34767693985f4b43?url=https%3A%2F%2Fi.imgur.com%2F0GPr11q.png)

**Comment by Nathat23** [comment]
Sorry for ignoring you...

I may use this in the StackMob 3 release.
