### ISSUE TITLE
Mobs dont Slit with error code

### ISSUE THREAD

**Issue by MysticCity** [Nathat23/StackMob-2#127]
**Describe the bug**
Stacked Mobs dont split after die

**Bukkit/Spigot AND StackMob version:**
1.12.2 with 2.2.16

**Additional context**
https://pastebin.com/18u6Lut7

**Comment by Nathat23** [comment]
this appears to be a problem with either mythicmobs or the mythicmobs configuration.

in the mythicmobs config, can you set "General.DebugLevel" to 2, then pastebin the latest.log file?

**Comment by MysticCity** [comment]
THX for this realy fast answer

Here is the last log with debig of 2:

https://pastebin.com/3hexC4RS

**Comment by MysticCity** [comment]
this test was with an creeper
but skeleton, zombies and and and dont work too

**Comment by Nathat23** [comment]
the problem is with mythicmobs vanillamobs overrides.
as a temporary 'solution' you can remove them from your config.

**Comment by MysticCity** [comment]
thats bad ^^

**Comment by Nathat23** [comment]
Fixed in f199541

**Comment by MysticCity** [comment]
Work perfect i love you thx
