### ISSUE TITLE
Stacked mobs disappearing

### ISSUE THREAD

**Issue by ecoterrorist** [Nathat23/StackMob-2#128]
**Describe the bug**
After updating to the latest version of the plugin, every so often stacks of mobs (only cows and chickens so far) go poof.

**To Reproduce**
Stack some passive mobs, feed them, wait around, leave the chunk, restart the server, etc.

**Expected behavior**
For the stacked mobs to not disappear.

**Screenshots/Videos**

**Bukkit/Spigot AND StackMob version:**
Spigot 1.13.2 Stackmob 2.4.7

**Additional context**

**Comment by Nathat23** [comment]
Could your provide a list of your plugins?

**Comment by ecoterrorist** [comment]
Sure, here it is.
![screen shot 2018-10-29 at 12 05 32 pm](https://user-images.githubusercontent.com/42695513/47663286-0405a180-db73-11e8-9f72-839c3896e7ed.png)

**Comment by Nathat23** [comment]
No idea why this would happen. Can you replicate with the latest version?

**Comment by Nathat23** [comment]
@ecoterrorist

**Comment by Nathat23** [comment]
Closing because of no response.
