### ISSUE TITLE
Drowned zombies

### ISSUE THREAD

**Issue by Nathat23** [Nathat23/StackMob-2#129]
Hey! Is there any chance you could make it so that a stack of zombies who drown, turn in to a stack of drowned zombies? Perhaps togglable with a config option.

When the stack turns in to a drowned, and is killed, the whole stack just dies. Unfortunately this is no good for drowned farming. 
(taken from https://www.spigotmc.org/threads/stackmob-enhance-your-servers-performance.184178/page-63#post-3204267)

**Comment by Nathat23** [comment]
To do this a new event in spigot will have to be created, so this may delay things for a while.

**Comment by GiraffeCubed** [comment]
This exists in PaperSpigot
https://papermc.io/javadocs/com/destroystokyo/paper/event/entity/EntityTransformedEvent.TransformedReason.html#DROWNED

Hopefully Spigot implements something similar soon.

**Comment by Nathat23** [comment]
I have added a fix for PaperSpigot users, hopefully it will get added to spigot as well.

**Comment by Nathat23** [comment]
This has been added into spigot as well.
