### ISSUE TITLE
Error with no ai

### ISSUE THREAD

**Issue by Nathat23** [Nathat23/StackMob-2#132]
Stackmob v3.0.1 have this feature, but have error
https://pastebin.com/rzu5Rtp8
@WindUnwaken

**Comment by Nathat23** [comment]
Can't reproduce @WindUnwaken

**Comment by WindUnwaken** [comment]
no-ai:
  enabled: true
  use-whitelist: true

only enabled doesn't have issue, but whitelist cause this

**Comment by Nathat23** [comment]
Fixed in next release.
