### ISSUE TITLE
This a big bug for 1.13.2

### ISSUE THREAD

**Issue by successed** [Nathat23/StackMob-2#137]
İ use the plugin bad, big problems check this video:

https://youtu.be/CyNM2bjlnTM

**Comment by Nathat23** [comment]
I couldn't tell by the video, did you spawn 5 or more sheep in the same area?

**Comment by successed** [comment]
Yes i spawned 12 entity sheeps and cutting wools it is a give me 3 drops

**Comment by Nathat23** [comment]
can you provide your config.yml?

**Comment by Olzie-12** [comment]
> can you provide your config.yml?

?? can you look on discord plz

**Comment by Nathat23** [comment]
@successed 
Make sure to restart not reload your server as well.

**Comment by Nathat23** [comment]
@successed please respond or this will be closed.
