### ISSUE TITLE
Drowned - Nautilus Shell Problem

### ISSUE THREAD

**Issue by BiGUNMAN** [Nathat23/StackMob-2#140]
**Is your feature request related to a problem? Please describe.**
Short: **Drowned** mobs drop drowned loot. **Drowned zombies** drop separate loot. Mob Stacker stacks **both** types of Drowned together. This results in their loot being mixed. 

Details: A natural spawned drowned can drop trident and nautilus as a "special" drop. Drowned zombies cannot drop the trident or nautilus as a loot. Because MobStacker merges them as a "Drowned", it becomes much easier to find these rarer loots because a zombie that drowns can drop them as well.

**Describe the solution you'd like**
Config option to enable/disable all zombie-drown being converted to normal drowned.

**Comment by Nathat23** [comment]
I'm not sure how a config option to disable the conversion would solve this?

Like a solution I can think of is to segregate entities depending if there is an item in their hand, but specifically for drowned entities as it would cause lag if it was for all types.
Or just prevent entities with the nautilus shell from stacking completely instead.

**Comment by BiGUNMAN** [comment]
I was suggesting a config option to separate the two entities (entities that become drowned vs entities that are created as drowned).

Or you could do what you suggested.

**Comment by LogGits** [comment]
But drowned zombies and drowned's the same mob:
https://minecraft.gamepedia.com/Drowned#Conversion

I think drowned zombies have same loot system as a drowned because it turns into that mob. Though i could be wrong.

**Comment by Nathat23** [comment]
@LogGits Naturally spawned drowned have a chance to spawn with tridents and nautilus shell.

**Comment by Nathat23** [comment]
Implemented.
