### ISSUE TITLE
Fall-Damage Mob Farms Broken

### ISSUE THREAD

**Issue by BiGUNMAN** [Nathat23/StackMob-2#141]
**Describe the bug**
Mob farms based on mobs dying from fall damage are broken. The entities fall but stay alive together.

**Expected behavior**
The grouped entities should die from the appropriate fall damage, regardless of if they are stacked. A config-option for this would work.

**Screenshots/Videos**
Not applicable.

**Bukkit/Spigot AND StackMob version:**
Not applicable (1.13, latest builds)

**Additional context**
Not applicable.

**Comment by Nathat23** [comment]
Isn't 'kill-step-damage' what you want?

**Comment by BiGUNMAN** [comment]
Maybe, doesn't`kill-step-damage` apply to all damage types, not strictly fall-damage?

**Comment by Nathat23** [comment]
there is a damage cause blacklist that can be used

**Comment by Nathat23** [comment]
I'm closing this because of resolution.
