### ISSUE TITLE
Ability to configure custom stack stick.

### ISSUE THREAD

**Issue by LogGits** [Nathat23/StackMob-2#143]
**Is your feature request related to a problem? Please describe.**
Stacking stick is also used for griefprevention. It would be useful to be able to change the stack stick Material.

**Comment by Nathat23** [comment]
Is this just for aesthetic or does it cause issues?

**Comment by LogGits** [comment]
It shows both griefprevention claim info and stack mob info. So i guess a bug, but it can be aesthetic 🙂

**Comment by Nathat23** [comment]
Implemented.

**Comment by LogGits** [comment]
Where can i get the download for this, is there by any chance a jenkins server?
