### ISSUE TITLE
Entities stacks after chunk unload/load

### ISSUE THREAD

**Issue by Getblock** [Nathat23/StackMob-2#146]
**Describe the bug**
Currently, I have 1.13 mobs on the list of that should not stack. It is not stacking if the chunk that the mobs are spawned are still loaded however if it becomes unloaded then loads, all of the mobs will combine.

**To Reproduce**

**Expected behavior**
The mobs should have not stacked at all since they are not on the list that should be stacking.

**Screenshots/Videos**

**Bukkit/Spigot AND StackMob version:**
Self explanatory. paperspigot 1.13.2
Stackmobs: v3.1.1

**Additional context**
Config:
# Don't stack if the entity is one of these types.
# List of the bukkit names can be found at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
no-stack-types:
    - TURTLE
    - COD
    - PUFFERFISH
    - SALMON
    - TROPICAL_FISH
    - PARROT
    - CHICKEN

**Comment by Nathat23** [comment]
Has been fixed.

**Comment by LogGits** [comment]
@Nathat23 is this related to #145? Cause after i closed it, I noticed it happen again.

**Comment by Nathat23** [comment]
@LogGits more than likely.
