### ISSUE TITLE
Stack health check

### ISSUE THREAD

**Issue by LogGits** [Nathat23/StackMob-2#147]
**Is your feature request related to a problem? Please describe.**
Mob farms that use a dropping system stack mobs with high health levels with others with lower health levels.

**Describe the solution you'd like**
Add an option to check if both mobs have the same health level before stacking.

**Additional context**
This is a solution to falldamage zombie farm.

**Comment by Nathat23** [comment]
Wouldn't it would be better if you wanted to preserve health the stacking of entities should become health based rather than stack value?

**Comment by LogGits** [comment]
The method that i proposed would prevent mobs that have fallen from the leftside and have taken damage, from stacking with ones that are swimming up the tunnel.
https://gyazo.com/a021a5196ddd389522fe288a2efd1909

While on paper it does sound like a good idea to stack based on health like you proposed, this would also change the dynamic. It would defeat the purpose of even dropping them.

**Comment by Nathat23** [comment]
@LogGits whats the name of this grinder?

**Comment by LogGits** [comment]
It's essentially a mob elevator and dropper design. There is a new one seen [here](https://www.reddit.com/r/Minecraft/comments/8lxibj/113aquatic_mob_water_elevator_no_ice/) I guess they are called [falldamage exp farm](https://www.youtube.com/watch?v=c_SXWIiXn2A).  Except this user had their drop close to the elevator to make it a more appealing design.

**Comment by Nathat23** [comment]
perhaps a delay before the first stack of an entity would help?

**Comment by LogGits** [comment]
A delay after spawning? Also if a stack of 4 fall down is there a way to make it so all 4 have the same health?

**Comment by Nathat23** [comment]
like a delay until the entity can stack after being spawned, so that new stacks with 20 health don't merge with stacks with like 5 health.

**Comment by LogGits** [comment]
Yea that would be cool

**Comment by Nathat23** [comment]
Implemented.
