### ISSUE TITLE
Rabbit stack

### ISSUE THREAD

**Issue by Getblock** [Nathat23/StackMob-2#149]
**Describe the bug**
Currently rabbits do stack "Sometimes", i have a bunch of rabbit in one fenced area however it takes awhile for them to stack or sometimes they never do. 

99% of the entities have no issue with stacking besides rabbit (probably how unique the entity is)

**Bukkit/Spigot AND StackMob version:**
Self explanatory.
Stackmob Version: v3.1.1
Paperspigot 1.13.2

On another note, you have fixed the unloading and loading stacking issue on my past bug report, not sure if there's a link where you upload builds for fixes. i kinda need that on the server.

**Comment by Nathat23** [comment]
Can't reproduce.

Can you pastebin your config.yml file?

**Comment by Nathat23** [comment]
@Getblock

**Comment by Nathat23** [comment]
Closing because of no response.
