### ISSUE TITLE
Unstacking stick

### ISSUE THREAD

**Issue by LogGits** [Nathat23/StackMob-2#15]
Is it possible to make a feature that allows us to add conditions to stacking. I am trying to make my stacking very specific.

Heres what i want to do:
- Only stack spawner/spawned mobs
- Leave naturally generated passive mobs alone and stop them from stacking
- Naturally spawned hostile mobs only stack if there is 5+ of the same mob near them

Also another cool feature would be an stacking wand/stick. With this item, when you rightclick the mob with the stick it unstacks them. When you left click them you stack nearby mobs. These would have permissions of course. stackmob.wand.stack, stackmob.wand.unstack. The stick would have a hidden enchant and could be customisable in the config to be renamed and have lore changed.

Keep up the great work with the plugin 🙂

**Comment by Nathat23** [comment]
You could probably do most of this in the current version config.

**Comment by Nathat23** [comment]
Completed in latest commits.
