### ISSUE TITLE
Stacked Mob custom drops

### ISSUE THREAD

**Issue by sandor111** [Nathat23/StackMob-2#154]
I would like to see a feature to where you can edit the drops of a stacked mob. Let's say for example: 
9x irongolem would drop 1 iron block. 
9x creeper would drop 1 tnt.
8x irongolem would drop ~8 iron
19x irongolem would drop 2 iron blocks

**Comment by Nathat23** [comment]
I'm not sure about the gunpower + tnt, but for nuggets, ingots and blocks this makes sense.

**Comment by sandor111** [comment]
That would also be also be perfect.
