### ISSUE TITLE
Mobs not stacking.

### ISSUE THREAD

**Issue by Getblock** [Nathat23/StackMob-2#159]
**Describe the bug**
The mobs are not stacking

**Expected behavior**
The mobs should be stacking because it came from spawner

**Screenshots/Videos**

**Bukkit/Spigot AND StackMob version:**
paperspigot 1.13.2
StackMob v.3.2.0

**Additional context**
https://pastebin.com/vz8bXLeM
The configuration is pasted on the link above.
![image](https://user-images.githubusercontent.com/43926892/49974179-02e9d180-ff73-11e8-81a7-59c998579481.png)

**Comment by Nathat23** [comment]
your config is set so stacking only works for chickens - remove CHICKEN from the 'stack-types' section.
