### ISSUE TITLE
Citizens being removed

### ISSUE THREAD

**Issue by ronc617** [Nathat23/StackMob-2#166]
**Describe the bug**

the command /sm removeall will remove a citizens NPC if it is a mob
is there a way to put a check in for this so they do not get removed while running that command ?

**To Reproduce**
Using citizens plugin creating a NPC that is mob
run command /sm removeall
it will delete the citizen mob

**Bukkit/Spigot AND StackMob version:**
spigot 1.13.2

**Comment by Nathat23** [comment]
Has been fixed.
