### ISSUE TITLE
Error Code After Server Start

### ISSUE THREAD

**Issue by MysticCity** [Nathat23/StackMob-2#24]
09.01.2018 16:47:10 [WARNING] [StackMob] Plugin StackMob v2.3.3 generated an exception while executing task 23
09.01.2018 16:47:10 java.util.ConcurrentModificationException: null
09.01.2018 16:47:10 	at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_151]
09.01.2018 16:47:10 	at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_151]
09.01.2018 16:47:10 	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getLivingEntities(CraftWorld.java:639) ~[spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
09.01.2018 16:47:10 	at uk.antiperson.stackmob.tools.cache.FlatCache.close(FlatCache.java:41) ~[?:?]
09.01.2018 16:47:10 	at uk.antiperson.stackmob.tasks.CacheTask.run(CacheTask.java:15) ~[?:?]
09.01.2018 16:47:10 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
09.01.2018 16:47:10 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
09.01.2018 16:47:10 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
09.01.2018 16:47:10 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
09.01.2018 16:47:10 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]

**Comment by Nathat23** [comment]
Will be fixed in next release.
