### ISSUE TITLE
Disabling AI

### ISSUE THREAD

**Issue by WizzleBear** [Nathat23/StackMob-2#25]
Since Spigot has its own mob-AI disabling system, StackMobs should be compatible with it. Meaning if it's enabled, any mobs combined together will still have no AI. Right now, StackMobs has a no-targeting AI disabler, but mobs still move around. Either disable mob movement or make the plugin compatible with that variable.

**Comment by GrizzsChannel** [comment]
BTW, can you make this only for spawned mobs and not natural mobs? Thanks!

**Comment by Nathat23** [comment]
Please make a new issue with your problem.
