### ISSUE TITLE
Could not pass event EntityDeathEvent

### ISSUE THREAD

**Issue by inpothet** [Nathat23/StackMob-2#27]
StackMob v2.3.2
TacoSpigot 1.8

I'm not fully sure that is happen but my guess is a player kills a stack of mobs which causes this to get triggered in the console/log

https://pastebin.com/qyTwwb0D

**Comment by Nathat23** [comment]
duplicate of #7

**Comment by inpothet** [comment]
I don't see how this is a duplicate as this is current on the default config

**Comment by inpothet** [comment]
I don't see how this is a duplicate as this is current on the default config
