### ISSUE TITLE
[Suggestion] Only stack spawner mobs

### ISSUE THREAD

**Issue by LogGits** [Nathat23/StackMob-2#28]
This would be an option in the config that makes it so entities that are spawned from a spawner get stacked. Every other mob would be ignored (unless specified in config).

e.g. if you only want spawners to stack mobs and normal guardian spawns you specify Stack-Spawner-Mobs and Include: Guardian.

**Comment by Nathat23** [comment]
Can't this already be done?

**Comment by GrizzsChannel** [comment]
Go to the 'no-stack-reasons:' section, and add this in:
```
    - 'BREEDING'
    - 'BUILD_IRONGOLEM'
    - 'BUILD_SNOWMAN'
    - 'BUILD_WITHER'
    - 'CHUNK_GEN'
    - 'CURED'
    - 'DEFAULT'
    - 'DISPENSE_EGG'
    - 'EGG'
    - 'ENDER_PEARL'
    - 'INFECTION'
    - 'JOCKEY'
    - 'LIGHTNING'
    - 'MOUNT'
    - 'NATURAL'
    - 'NETHER_PORTAL'
    - 'OCELOT_BABY'
    - 'REINFORCEMENTS'
    - 'SHOULDER_ENTITY'
    - 'SILVERFISH_BLOCK'
    - 'SLIME_SPLIT'
    - 'SPAWNER_EGG'
    - 'TRAP'
    - 'VILLAGE_DEFENSE'
    - 'VILLAGE_INVASION'
```
That should only allow plugin-spawned mobs and spawner-spawned mobs to be stacked.

**Comment by LogGits** [comment]
Fantastic, I will test this out tomorrow morning :)
