### ISSUE TITLE
Plugin cannot be loaded 

### ISSUE THREAD

**Issue by Guhenriques** [Nathat23/StackMob-2#288]
Its not possible to run on 1.12??????

16.01 20:48:52 [Server] ERROR Error occurred while enabling StackMob v5.0.2 (Is it up to date?)
16.01 20:48:52 [Server] INFO java.lang.NoClassDefFoundError: org/bukkit/entity/Mob
16.01 20:48:52 [Server] INFO at uk.antiperson.stackmob.config.EntityTranslation.createFile(EntityTranslation.java:26) ~[?:?]
16.01 20:48:52 [Server] INFO at uk.antiperson.stackmob.config.ConfigFile.load(ConfigFile.java:72) ~[?:?]
16.01 20:48:52 [Server] INFO at uk.antiperson.stackmob.StackMob.loadConfig(StackMob.java:108) ~[?:?]
16.01 20:48:52 [Server] INFO at uk.antiperson.stackmob.StackMob.onEnable(StackMob.java:62) ~[?:?]
16.01 20:48:52 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
16.01 20:48:52 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
16.01 20:48:52 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
16.01 20:48:52 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
16.01 20:48:52 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
16.01 20:48:52 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
16.01 20:48:52 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
16.01 20:48:52 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
16.01 20:48:52 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
16.01 20:48:52 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
16.01 20:48:52 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

**Comment by ploppyperson** [comment]
No. 1.15 only.
