### ISSUE TITLE
Urgent: Server crashes

### ISSUE THREAD

**Issue by InstantlyMoist** [Nathat23/StackMob-2#3]
Hello,

I've been having server issues lately, not being able to figure it out. Untill it crashed again and I was in time to read the stracktraces.
https://hastebin.com/ginanahari.vbs

It's a plugin sided issue with chickens (i think) that lay eggs.

There is also another error:
https://hastebin.com/rigepasedi.css

Sorry for this format, my host sent me this.

**Comment by Nathat23** [comment]
The second error isn't anything to do with StackMob, however it is strange you are getting the first error.
I noticed another plugin in that stacktrace, BlowableObsidians, try removing it and see if it happens again.

**Comment by InstantlyMoist** [comment]
The error had to do with unsafe drops coming from your plugins, I've had contact with other plugin developers and the way you drop items (without checks) is causing for issues in the plugin.

**Comment by Nathat23** [comment]
What part of the dropping is unsafe? The spawning of several stacks at once?

**Comment by InstantlyMoist** [comment]
A developer in the CodeVision discord chat said those were unsafe:
https://rubbaboy.me/images/8dlnzrt.png 
https://rubbaboy.me/images/3khhjhf.png

**Comment by Nathat23** [comment]
Could you ask the developer to look at the code on github instead? The decompiled code is slightly different then on here.

**Comment by Nathat23** [comment]
That is indeed where the error is coming from.

**Comment by Nathat23** [comment]
Could you send me your full log file?

**Comment by Nathat23** [comment]
Could you upload your full server log?

**Comment by InstantlyMoist** [comment]
Sorry I don't have it anymore. The error is probably the only thing what you need. I deleted the plugin due those crashes causing some of my plugins to not save data right, wich caused data loses

**Comment by Nathat23** [comment]
The problem with what you've provided is that it doesn't tell me what the error is, it only tells me that there was an error on that line.

**Comment by Nathat23** [comment]
I will try and see if I can reproduce the error though.
