### ISSUE TITLE
Unknown bug

### ISSUE THREAD

**Issue by johnsoncui02** [Nathat23/StackMob-2#30]
Stackmob Version: 2.2.5
Spigot Version: 1.12.2 snapshot.

> [01:33:08 WARN]: [StackMob] Task #21 for StackMob v2.2.5 generated an exception
java.lang.NullPointerException: null

**Comment by Nathat23** [comment]
Can you give me the full error?

**Comment by johnsoncui03** [comment]
Unfortunately that is the full error. It repeats itself however. It might of produced this error due to some sort of typo I had however, after resetting the config file completely it was fine again. Sorry about this trouble
