### ISSUE TITLE
Mob Killed All At Once [Not One by One]

### ISSUE THREAD

**Issue by xinxcode** [Nathat23/StackMob-2#33]
I was trying to changing and changing the config (even default too) of the plugin, but still all the mob will death while one mob is death.
I think this plugin have problem with SpawnersOnly or SilkSpawners plugin.
But I use default configuration of those both plugin.
Please help.

**Comment by xinxcode** [comment]
`# StackMob 2 created by antiPerson.
# Report issues that you have experienced in the discussion thread.

# The size of the area around an entity that should be checked for matching entities to stack with.
check-area:
    x: 7
    y: 4
    z: 7

# Everything related to the tag seen above entities
tag:
   # The formatting of the tag.
    # Placeholders:
    # %size% - Stack size.
    # %type% - Formatted type name.
    # %bukkit_type% - The entity type as bukkit calls it.
    # Normal Minecraft color codes are also supported, by using '&' before the letter/number.
    format: '&d%size%x &6%type%'
    # Whether the tag above the entity should be seen at all times, or only when hovering over.
    always-visible: true
    # If the stack size if equal to or below this number, don't show the tag.
    remove-at: 1
    # Only show the name tag if the player is near the entity.
    show-player-nearby:
        enabled: true
        # Only display the tag to the player if the player is in this area of the entity.
        x: 10
        y: 3
        z: 10


 # Custom rules for specific entities.
custom:
   # Example (remove hashtags to make this work):
    #PIG:
    #    stack-max: 25
    #    tag:
    #        format: '%size%x Piggy'
    #        always-visible: true
    #        remove-at: 1

# The delay between each time the stacking task is ran (in ticks.)
task-delay: 100
# The maximum size a single stack can be.
stack-max: 20
# If bigger stacks should get priority when stacking on the task.
big-priority: true
# If the entity was spawned by these causes, then don't stack.
# Reasons list can be found at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
no-stack-reasons:
   - ''
# Don't stack if the entity is one of these types.
# List of the bukkit names can be found at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
no-stack-types:
   - ''
# If the entity is located in one of these worlds, then don't stack.
no-stack-worlds:
   - ''
# Don't stack until there are more than the number specified of entities of the same type in the check area set above.
# Set to 0 to disable this feature.
dont-stack-until: 3

# Enables/disables the comparing of mob type specific attributes before stacking together.
compare:
    villager-profession: true
    sheep-wool-sheared: true
    sheep-wool-color: true
    slime-size: true
    horse-color: true
    # Apply to more than one type of entity.
    entity-age: true
    can-breed: true
    # Only for 1.8.x and below.
    zombie-is-villager: true
    # Only 1.10.x and below.
    skeleton-type: true
    zombie-villager-profession: true
    # 1.11 and above.
    llama-color: true
    # 1.12 and above.
    parrot-color: true

# Check these attributes before stacking.
check:
    tamed: true
    leashed: true
    is-miniature-pet: true

# Things that should be duplicated.
multiply:
    # Make creeper explosions bigger
     creeper-explosion: true
     # Chicken lay eggs, so make more eggs be dropped
     chicken-eggs: true
     # When sheep are sheared, multiply all the wool.
     sheep-wool: false
     # Multiply mushrooms for all of the cows.
     mooshroom-mushrooms: false
     # Multiply the amount of small slimes spawned when a big slime is killed.
     small-slimes: true
     # When an entity is fed it's food, spawn a new stack with the correct number of children.
     breed: true

# If the stack should split into more when these things happen.
divide-on:
   # If sheep should split into serperate stacks when sheared.
    sheep-shear: true
    # If dying sheep should cause the stack to split.
    sheep-dye: true
    # When a mooshroom gets sheared, spilt the stack.
    mooshroom-shear: true
    # When a stack is fed it's food, spilt, so the stack can be bred.
    breed: true
    # When a player tames an entity.
    tame: true
    # When an entity it named using a nametag.
    name: true

# Make every entity die in the stack on death.
kill-all:
    enabled: false
    # DeathEvent reasons that shouldn't trigger kill-all.
    # List of bukkit names for death reasons can be found at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html
    reason-blacklist:
       - ''
    # Entity types that shouldn't trigger kill-all.
    type-blacklist:
       - 'COW'

# Only kill some of the stack
kill-step:
    enabled: false
    # DeathEvent reasons that shouldn't trigger kill-step.
    # List of bukkit names for death reasons can be found at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html
    reason-blacklist:
       - ''
    # Entity types that shouldn't trigger kill-step.
    type-blacklist:
       - 'COW'
    # The maximum amount by which the stack should decrease by.
    max-step: 1

# Multiply the amount of drops depending on the size of the stack killed.
# Only needed if kill-all OR kill-step is enabled above.
multiply-drops:
    enabled: true
    # Item types that should be duplicated.
    # A list of materials can be found at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
    drops-whitelist:
        - STRING
        - SULPHUR
        - ROTTEN_FLESH
        - BONE
        - BLAZE_ROD
        - GHAST_TEAR
        - ENDER_PEARL
        - MAGMA_CREAM
        - ARROW
        - SLIME_BALL
        - COOKED_BEEF
        - COOKED_CHICKEN
        - COOKED_MUTTON
        - COOKED_RABBIT
        - GRILLED_PORK
        - RAW_BEEF
        - RAW_CHICKEN
        - MUTTON
        - PORK
        - RABBIT
        - FEATHER
        - RED_MUSHROOM
        - LEATHER
        - RABBIT_FOOT
        - RABBIT_HIDE
        - NETHER_STAR
        - GLASS_BOTTLE
        - GLOWSTONE_DUST
        - REDSTONE
        - SPIDER_EYE
        - SUGAR
        - STICK
        - IRON_INGOT
        - GOLD_NUGGET
        - GOLD_INGOT
        - PRISMARINE_SHARD
        - EMERALD
    # Only drop one item per entity.
    drop-one-per:
        - EMERALD
        - NETHER_STAR
        - TOTEM

# Multiplies the experience dropped on kill-all/kill-step.
multiply-exp-enabled: true

# Multiplies the damage that an entity gives to the player.
multiply-damage-done: false

# Multiplies the damage that the entities receives, if multiplied damage is more than the max health, remove stacks.
multiply-damage-received:
    enabled: false
    # Blacklist of damage causes.
    cause-blacklist:
       - ''

# Prevent entities from targeting players.
# Like no-ai but the entities can move.
no-targeting:
    enabled: true
    types-blacklist:
      - ''

# Everything to do with mcMMO
mcmmo:
   # Give no mcmmo experience
    no-experience:
        enabled: false
        # Blacklist of entity types that should still give mcmmo experience.
        blacklist:
           - ''
mythicmobs:
   # If Mythicmobs should stack together
    enabled: false
    # MythicMob types that shouldn't stack, use the 'internal name'
    blacklist:
      - ''

# If WorldGuard is installed, enable support for it.
worldguard-support: true`

**Comment by xinxcode** [comment]
> # StackMob 2 created by antiPerson.
# Report issues that you have experienced in the discussion thread.

# The size of the area around an entity that should be checked for matching entities to stack with.
check-area:
    x: 7
    y: 4
    z: 7

# Everything related to the tag seen above entities
tag:
   # The formatting of the tag.
    # Placeholders:
    # %size% - Stack size.
    # %type% - Formatted type name.
    # %bukkit_type% - The entity type as bukkit calls it.
    # Normal Minecraft color codes are also supported, by using '&' before the letter/number.
    format: '&d%size%x &6%type%'
    # Whether the tag above the entity should be seen at all times, or only when hovering over.
    always-visible: true
    # If the stack size if equal to or below this number, don't show the tag.
    remove-at: 1
    # Only show the name tag if the player is near the entity.
    show-player-nearby:
        enabled: true
        # Only display the tag to the player if the player is in this area of the entity.
        x: 10
        y: 3
        z: 10


 # Custom rules for specific entities.
custom:
   # Example (remove hashtags to make this work):
    #PIG:
    #    stack-max: 25
    #    tag:
    #        format: '%size%x Piggy'
    #        always-visible: true
    #        remove-at: 1

# The delay between each time the stacking task is ran (in ticks.)
task-delay: 100
# The maximum size a single stack can be.
stack-max: 20
# If bigger stacks should get priority when stacking on the task.
big-priority: true
# If the entity was spawned by these causes, then don't stack.
# Reasons list can be found at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
no-stack-reasons:
   - ''
# Don't stack if the entity is one of these types.
# List of the bukkit names can be found at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
no-stack-types:
   - ''
# If the entity is located in one of these worlds, then don't stack.
no-stack-worlds:
   - ''
# Don't stack until there are more than the number specified of entities of the same type in the check area set above.
# Set to 0 to disable this feature.
dont-stack-until: 3

# Enables/disables the comparing of mob type specific attributes before stacking together.
compare:
    villager-profession: true
    sheep-wool-sheared: true
    sheep-wool-color: true
    slime-size: true
    horse-color: true
    # Apply to more than one type of entity.
    entity-age: true
    can-breed: true
    # Only for 1.8.x and below.
    zombie-is-villager: true
    # Only 1.10.x and below.
    skeleton-type: true
    zombie-villager-profession: true
    # 1.11 and above.
    llama-color: true
    # 1.12 and above.
    parrot-color: true

# Check these attributes before stacking.
check:
    tamed: true
    leashed: true
    is-miniature-pet: true

# Things that should be duplicated.
multiply:
    # Make creeper explosions bigger
     creeper-explosion: true
     # Chicken lay eggs, so make more eggs be dropped
     chicken-eggs: true
     # When sheep are sheared, multiply all the wool.
     sheep-wool: false
     # Multiply mushrooms for all of the cows.
     mooshroom-mushrooms: false
     # Multiply the amount of small slimes spawned when a big slime is killed.
     small-slimes: true
     # When an entity is fed it's food, spawn a new stack with the correct number of children.
     breed: true

# If the stack should split into more when these things happen.
divide-on:
   # If sheep should split into serperate stacks when sheared.
    sheep-shear: true
    # If dying sheep should cause the stack to split.
    sheep-dye: true
    # When a mooshroom gets sheared, spilt the stack.
    mooshroom-shear: true
    # When a stack is fed it's food, spilt, so the stack can be bred.
    breed: true
    # When a player tames an entity.
    tame: true
    # When an entity it named using a nametag.
    name: true

# Make every entity die in the stack on death.
kill-all:
    enabled: false
    # DeathEvent reasons that shouldn't trigger kill-all.
    # List of bukkit names for death reasons can be found at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html
    reason-blacklist:
       - ''
    # Entity types that shouldn't trigger kill-all.
    type-blacklist:
       - 'COW'

# Only kill some of the stack
kill-step:
    enabled: false
    # DeathEvent reasons that shouldn't trigger kill-step.
    # List of bukkit names for death reasons can be found at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html
    reason-blacklist:
       - ''
    # Entity types that shouldn't trigger kill-step.
    type-blacklist:
       - 'COW'
    # The maximum amount by which the stack should decrease by.
    max-step: 1

# Multiply the amount of drops depending on the size of the stack killed.
# Only needed if kill-all OR kill-step is enabled above.
multiply-drops:
    enabled: true
    # Item types that should be duplicated.
    # A list of materials can be found at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
    drops-whitelist:
        - STRING
        - SULPHUR
        - ROTTEN_FLESH
        - BONE
        - BLAZE_ROD
        - GHAST_TEAR
        - ENDER_PEARL
        - MAGMA_CREAM
        - ARROW
        - SLIME_BALL
        - COOKED_BEEF
        - COOKED_CHICKEN
        - COOKED_MUTTON
        - COOKED_RABBIT
        - GRILLED_PORK
        - RAW_BEEF
        - RAW_CHICKEN
        - MUTTON
        - PORK
        - RABBIT
        - FEATHER
        - RED_MUSHROOM
        - LEATHER
        - RABBIT_FOOT
        - RABBIT_HIDE
        - NETHER_STAR
        - GLASS_BOTTLE
        - GLOWSTONE_DUST
        - REDSTONE
        - SPIDER_EYE
        - SUGAR
        - STICK
        - IRON_INGOT
        - GOLD_NUGGET
        - GOLD_INGOT
        - PRISMARINE_SHARD
        - EMERALD
    # Only drop one item per entity.
    drop-one-per:
        - EMERALD
        - NETHER_STAR
        - TOTEM

# Multiplies the experience dropped on kill-all/kill-step.
multiply-exp-enabled: true

# Multiplies the damage that an entity gives to the player.
multiply-damage-done: false

# Multiplies the damage that the entities receives, if multiplied damage is more than the max health, remove stacks.
multiply-damage-received:
    enabled: false
    # Blacklist of damage causes.
    cause-blacklist:
       - ''

# Prevent entities from targeting players.
# Like no-ai but the entities can move.
no-targeting:
    enabled: true
    types-blacklist:
      - ''

# Everything to do with mcMMO
mcmmo:
   # Give no mcmmo experience
    no-experience:
        enabled: false
        # Blacklist of entity types that should still give mcmmo experience.
        blacklist:
           - ''
mythicmobs:
   # If Mythicmobs should stack together
    enabled: false
    # MythicMob types that shouldn't stack, use the 'internal name'
    blacklist:
      - ''

# If WorldGuard is installed, enable support for it.
worldguard-support: true

**Comment by xinxcode** [comment]
> # StackMob 2 created by antiPerson.
# Report issues that you have experienced in the discussion thread.

# The size of the area around an entity that should be checked for matching entities to stack with.
check-area:
    x: 7
    y: 4
    z: 7

# Everything related to the tag seen above entities
tag:
   # The formatting of the tag.
    # Placeholders:
    # %size% - Stack size.
    # %type% - Formatted type name.
    # %bukkit_type% - The entity type as bukkit calls it.
    # Normal Minecraft color codes are also supported, by using '&' before the letter/number.
    format: '&d%size%x &6%type%'
    # Whether the tag above the entity should be seen at all times, or only when hovering over.
    always-visible: true
    # If the stack size if equal to or below this number, don't show the tag.
    remove-at: 1
    # Only show the name tag if the player is near the entity.
    show-player-nearby:
        enabled: true
        # Only display the tag to the player if the player is in this area of the entity.
        x: 10
        y: 3
        z: 10


 # Custom rules for specific entities.
custom:
   # Example (remove hashtags to make this work):
    #PIG:
    #    stack-max: 25
    #    tag:
    #        format: '%size%x Piggy'
    #        always-visible: true
    #        remove-at: 1

# The delay between each time the stacking task is ran (in ticks.)
task-delay: 100
# The maximum size a single stack can be.
stack-max: 20
# If bigger stacks should get priority when stacking on the task.
big-priority: true
# If the entity was spawned by these causes, then don't stack.
# Reasons list can be found at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
no-stack-reasons:
   - ''
# Don't stack if the entity is one of these types.
# List of the bukkit names can be found at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
no-stack-types:
   - ''
# If the entity is located in one of these worlds, then don't stack.
no-stack-worlds:
   - ''
# Don't stack until there are more than the number specified of entities of the same type in the check area set above.
# Set to 0 to disable this feature.
dont-stack-until: 3

# Enables/disables the comparing of mob type specific attributes before stacking together.
compare:
    villager-profession: true
    sheep-wool-sheared: true
    sheep-wool-color: true
    slime-size: true
    horse-color: true
    # Apply to more than one type of entity.
    entity-age: true
    can-breed: true
    # Only for 1.8.x and below.
    zombie-is-villager: true
    # Only 1.10.x and below.
    skeleton-type: true
    zombie-villager-profession: true
    # 1.11 and above.
    llama-color: true
    # 1.12 and above.
    parrot-color: true

# Check these attributes before stacking.
check:
    tamed: true
    leashed: true
    is-miniature-pet: true

# Things that should be duplicated.
multiply:
    # Make creeper explosions bigger
     creeper-explosion: true
     # Chicken lay eggs, so make more eggs be dropped
     chicken-eggs: true
     # When sheep are sheared, multiply all the wool.
     sheep-wool: false
     # Multiply mushrooms for all of the cows.
     mooshroom-mushrooms: false
     # Multiply the amount of small slimes spawned when a big slime is killed.
     small-slimes: true
     # When an entity is fed it's food, spawn a new stack with the correct number of children.
     breed: true

# If the stack should split into more when these things happen.
divide-on:
   # If sheep should split into serperate stacks when sheared.
    sheep-shear: true
    # If dying sheep should cause the stack to split.
    sheep-dye: true
    # When a mooshroom gets sheared, spilt the stack.
    mooshroom-shear: true
    # When a stack is fed it's food, spilt, so the stack can be bred.
    breed: true
    # When a player tames an entity.
    tame: true
    # When an entity it named using a nametag.
    name: true

# Make every entity die in the stack on death.
kill-all:
    enabled: false
    # DeathEvent reasons that shouldn't trigger kill-all.
    # List of bukkit names for death reasons can be found at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html
    reason-blacklist:
       - ''
    # Entity types that shouldn't trigger kill-all.
    type-blacklist:
       - 'COW'

# Only kill some of the stack
kill-step:
    enabled: false
    # DeathEvent reasons that shouldn't trigger kill-step.
    # List of bukkit names for death reasons can be found at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html
    reason-blacklist:
       - ''
    # Entity types that shouldn't trigger kill-step.
    type-blacklist:
       - 'COW'
    # The maximum amount by which the stack should decrease by.
    max-step: 1

# Multiply the amount of drops depending on the size of the stack killed.
# Only needed if kill-all OR kill-step is enabled above.
multiply-drops:
    enabled: true
    # Item types that should be duplicated.
    # A list of materials can be found at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
    drops-whitelist:
        - STRING
        - SULPHUR
        - ROTTEN_FLESH
        - BONE
        - BLAZE_ROD
        - GHAST_TEAR
        - ENDER_PEARL
        - MAGMA_CREAM
        - ARROW
        - SLIME_BALL
        - COOKED_BEEF
        - COOKED_CHICKEN
        - COOKED_MUTTON
        - COOKED_RABBIT
        - GRILLED_PORK
        - RAW_BEEF
        - RAW_CHICKEN
        - MUTTON
        - PORK
        - RABBIT
        - FEATHER
        - RED_MUSHROOM
        - LEATHER
        - RABBIT_FOOT
        - RABBIT_HIDE
        - NETHER_STAR
        - GLASS_BOTTLE
        - GLOWSTONE_DUST
        - REDSTONE
        - SPIDER_EYE
        - SUGAR
        - STICK
        - IRON_INGOT
        - GOLD_NUGGET
        - GOLD_INGOT
        - PRISMARINE_SHARD
        - EMERALD
    # Only drop one item per entity.
    drop-one-per:
        - EMERALD
        - NETHER_STAR
        - TOTEM

# Multiplies the experience dropped on kill-all/kill-step.
multiply-exp-enabled: true

# Multiplies the damage that an entity gives to the player.
multiply-damage-done: false

# Multiplies the damage that the entities receives, if multiplied damage is more than the max health, remove stacks.
multiply-damage-received:
    enabled: false
    # Blacklist of damage causes.
    cause-blacklist:
       - ''

# Prevent entities from targeting players.
# Like no-ai but the entities can move.
no-targeting:
    enabled: true
    types-blacklist:
      - ''

# Everything to do with mcMMO
mcmmo:
   # Give no mcmmo experience
    no-experience:
        enabled: false
        # Blacklist of entity types that should still give mcmmo experience.
        blacklist:
           - ''
mythicmobs:
   # If Mythicmobs should stack together
    enabled: false
    # MythicMob types that shouldn't stack, use the 'internal name'
    blacklist:
      - ''

# If WorldGuard is installed, enable support for it.
worldguard-support: true<

**Comment by xinxcode** [comment]
`kill-all:`
    enabled: false
    # DeathEvent reasons that shouldn't trigger kill-all.
    # List of bukkit names for death reasons can be found at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html
    reason-blacklist:
       - ''
    # Entity types that shouldn't trigger kill-all.
    type-blacklist:
       - 'COW'

# Only kill some of the stack
kill-step:
    enabled: false
    # DeathEvent reasons that shouldn't trigger kill-step.
    # List of bukkit names for death reasons can be found at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html
    reason-blacklist:
       - ''
    # Entity types that shouldn't trigger kill-step.
    type-blacklist:
       - 'COW'
    # The maximum amount by which the stack should decrease by.
    max-step: 1
# Multiplies the damage that the entities receives, if multiplied damage is more than the max health, remove stacks.
multiply-damage-received:
    enabled: false
    # Blacklist of damage causes.
    cause-blacklist:
       - ''``

**Comment by xinxcode** [comment]
kill-all:
enabled: false
# DeathEvent reasons that shouldn't trigger kill-all.
# List of bukkit names for death reasons can be found at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html
reason-blacklist:
- ''
# Entity types that shouldn't trigger kill-all.
type-blacklist:
- 'COW'

kill-step:
enabled: false
# DeathEvent reasons that shouldn't trigger kill-step.
# List of bukkit names for death reasons can be found at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html
reason-blacklist:
- ''
# Entity types that shouldn't trigger kill-step.
type-blacklist:
- 'COW'
# The maximum amount by which the stack should decrease by.
max-step: 1

multiply-damage-received:
enabled: false
# Blacklist of damage causes.
cause-blacklist:
- ''``

**Comment by xinxcode** [comment]
kill-all:
enabled: false
reason-blacklist:
- ''
type-blacklist:
- 'COW'

kill-step:
enabled: false
reason-blacklist:
- ''
type-blacklist:
- 'COW'
max-step: 1

multiply-damage-received:
enabled: false
cause-blacklist:
- ''``

**Comment by Nathat23** [comment]
Please use pastebin to post your error.

**Comment by xinxcode** [comment]
No there's no error in the server log.
But I don't know why the config work well, I was tried all of your suggestion on the other issue comment.
But it still, the mob will death in a stack, not one by one.
This is my config:
https://hastebin.com/canibakiqo.coffeescript
And if you want to see my SpawnersOnly or SilkSpawners:
SpawnersOnly:
https://hastebin.com/esapobapik.bash
SilkSpawners:
https://hastebin.com/fupomedezi.bash
Thanks

**Comment by Nathat23** [comment]
I have tested just now, and this it works fine.

Try spawning a mob using the '/sm spawnstack' command, does this still occur?

**Comment by Nathat23** [comment]
Any update?

**Comment by xinxcode** [comment]
Im sorry, this all because SpawnersOnly plugin.
It only allowed mob spawning from spawner, so it'll kill all stacked mob maybe because stacked mob system like spawning next mob after the first mob is die.
Now it will be easy if I use gamrule, but Im not sure how I disabled animal spawning in the world.
