### ISSUE TITLE
[suggestion] Max-stacked entities drops

### ISSUE THREAD

**Issue by TheIronMinerLv** [Nathat23/StackMob-2#34]
A simple yet powerful suggestion - make so it is configurable how many stacked drops will drop when a stack of something dies.

An example: Max-stack-drops in config is set to 2000. If 4000 stacked pigs dies from fall (and their loot is multiplied), only 2000 drops will drop.

Why? Players in my server are abusing this and lagging it by killing thousands of entities in one spot. Please add this!

**Comment by Nathat23** [comment]
I could add a option for how many mobs the drops get multiplied for?

**Comment by TheIronMinerLv** [comment]
Yes, that would be good enough too if that would basically fix this small issue.

**Comment by TheIronMinerLv** [comment]
When could you add this feature? My players are lagging my server :(

**Comment by TheIronMinerLv** [comment]
@Nathat23 could you elaborate?
