### ISSUE TITLE
Console Spam StackMob v2.2.7

### ISSUE THREAD

**Issue by anilcan44** [Nathat23/StackMob-2#36]
Version: 1.8.8 paperspigot

>  [Server thread/WARN]: [StackMob] Task #5 for StackMob v2.2.7 generated an exception
> java.lang.NullPointerException
> 	at com.comphenix.protocol.wrappers.WrappedDataWatcher$WrappedDataWatcherObject.newHandle(WrappedDataWatcher.java:703) ~[?:?]
> 	at com.comphenix.protocol.wrappers.WrappedDataWatcher$WrappedDataWatcherObject.<init>(WrappedDataWatcher.java:690) ~[?:?]
> 	at uk.antiperson.stackmob.tools.plugin.ProtocolSupport.sendUpdatePacket(ProtocolSupport.java:33) ~[?:?]
> 	at uk.antiperson.stackmob.tasks.TagTask.run(TagTask.java:74) ~[?:?]
> 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[spigot.jar:git-PaperSpigot-"4c7641d"]
> 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [spigot.jar:git-PaperSpigot-"4c7641d"]
> 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [spigot.jar:git-PaperSpigot-"4c7641d"]
> 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-"4c7641d"]
> 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot.jar:git-PaperSpigot-"4c7641d"]
> 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot.jar:git-PaperSpigot-"4c7641d"]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by Nathat23** [comment]
I can't seem to reproduce.

Does updating to the latest protocollib from https://github.com/dmulloy2/ProtocolLib/ solve anything?

**Comment by Nathat23** [comment]
Will be fixed in next version.
