### ISSUE TITLE
TagTask takes over 500% of tick

### ISSUE THREAD

**Issue by Behoston** [Nathat23/StackMob-2#39]
Probably too many chicken produces eggs same time.

https://timings.aikar.co/?id=e82dbb26b1674b9cbc2a2ecc46dd0f43

plugin config:
https://gist.github.com/Behoston/1922fab5deb66e19cbfc74e8a99f025b

Best solution for now for me is disable tag task.

You should't use nested for-loops for updating tags. Better way to do this is collect all visible entities, then modify tags in separate loop. Now you can apply tag changes for given entity more than once (if two players are nearby to entity, you change tag twice).

**Comment by Nathat23** [comment]
Yeah, the current way of doing things is inefficient and could be massively improved.

**Comment by Nathat23** [comment]
If this still occurs, please create a new issue.
