### ISSUE TITLE
Use values from config

### ISSUE THREAD

**Issue by Behoston** [Nathat23/StackMob-2#40]
Why not use values provided by user in config files?

https://github.com/Nathat23/StackMob-2/blob/261abad8235c10e9b8785e445a0a1fa8f4326e7f/src/main/java/uk/antiperson/stackmob/tasks/TagTask.java#L26
https://github.com/Nathat23/StackMob-2/blob/261abad8235c10e9b8785e445a0a1fa8f4326e7f/src/main/java/uk/antiperson/stackmob/tasks/TagTask.java#L72

https://github.com/Nathat23/StackMob-2/blob/261abad8235c10e9b8785e445a0a1fa8f4326e7f/src/main/resources/config.yml#L25-L31

**Comment by Nathat23** [comment]
Because they work whether or not the 'show-player-nearby' feature is enabled.
