### ISSUE TITLE
All option for mythicmobs

### ISSUE THREAD

**Issue by MysticCity** [Nathat23/StackMob-2#41]
mythicmobs:
   # If Mythicmobs should stack together
    enabled: true
    # MythicMob types that shouldn't stack, use the 'internal name'
    blacklist:
      - 'Zombie-Lord'

what is wrong here ???
The Zombie-Lord stack with all other zombies

**Comment by Nathat23** [comment]
Is that the internal name that MythicMobs uses?

**Comment by MysticCity** [comment]
Yes

**Comment by MysticCity** [comment]
all names mobs stack.... all Mythicmobs stack.....

**Comment by MysticCity** [comment]
so i testet it now with 10 mm mobs
and all monsters stack together with normal vanilla monster

**Comment by Nathat23** [comment]
Can you show me your mythicmobs file for that mob?

**Comment by MysticCity** [comment]
sure

![unbenannt](https://user-images.githubusercontent.com/6275962/38308985-023508a8-3819-11e8-8c7e-f2a22f077765.png)

**Comment by MysticCity** [comment]
![unbenannt](https://user-images.githubusercontent.com/6275962/38309051-3481177a-3819-11e8-9a77-a9532f6f6081.png)

**Comment by Nathat23** [comment]
Fixed in latest version.

**Comment by MysticCity** [comment]
is there an option to prevent all mm mobs

like

'ALL'

**Comment by Nathat23** [comment]
not currently

**Comment by MysticCity** [comment]
can you add this
because we have over 189 mobs now and we planed up to 300+ and alld mobs without stacking
