### ISSUE TITLE
Ability to kill one from stack using api

### ISSUE THREAD

**Issue by Hawkite** [Nathat23/StackMob-2#44]
Hello, I would like a functionality added to the api which allows you to kill a single entity in the stack. Right now in order to kill them (without killing the whole stack) I have to add fall damage to them which sometimes causes multiple to die.

**Comment by Nathat23** [comment]
This can be done by using the #setSize(int) method in the StackedEntity class.

**Comment by Hawkite** [comment]
setSize doesn't have items drop, which I want. It just changes the size of the stack.

**Comment by Nathat23** [comment]
I'll add something in the API for this then.

**Comment by Hawkite** [comment]
the method killSingleNaturally() doesn't work properly. 

1. It kills the whole stack.
2. It doesn't drop anything.

**Comment by Nathat23** [comment]
Could you put this into a new issue?
