### ISSUE TITLE
Kill-Step dependant on damage.

### ISSUE THREAD

**Issue by WizzleBear** [Nathat23/StackMob-2#45]
Does it go off of damage done? So, if set it to 10 and use a normal diamond sword to kill a mob, will it kill one instead of 10? If not, that would be a cool feature if it counts all the damage done to the mobs and kills them accordingly.

**Comment by Nathat23** [comment]
Nope, could probably be added.

**Comment by Nathat23** [comment]
do you mean like if you did 5 damage then the damage would be multiplied for each mob? or just if more damage than the entities health is dealt, then remove the amount of entities that could be killed by that damage?

**Comment by Nathat23** [comment]
please respond - this is delaying development.

**Comment by WizzleBear** [comment]
If I did 5 damage and it only takes 3 damage to kill the mob, the 2 would go onto the next mob.
