### ISSUE TITLE
Passive mobs not stacking?

### ISSUE THREAD

**Issue by mrcoffee1026** [Nathat23/StackMob-2#46]
Although I have not disallowed it, mobs like sheep, villagers, cows, chicken, whatever... none of them seem to be stacking.  Hostile mobs in grinders seem to be stacking as they should.  While I've set no spawn reasons for mobs to NOT be stacked... do preexisting mobs on the server not stack?  Do mobs have to spawn with the plugin active in order to be stacked?  Trying to come up with any reason it might have for not doing anything.  I spawned like 8 nitwit Villagers in a small area and they didn't stack either... the plugin was running during that time.  Even though I had "villager-profession: true" these should have stacked, I think.

**Comment by mrcoffee1026** [comment]
well nevermind about the villagers... realized my limit was at 10... when i dropped it 5, they stacked.  But my sheep/cows... no other non-hostiles seem to.

**Comment by mrcoffee1026** [comment]
And... you may not be able to do anything about this... but this would be awesome for golem farms... except that the stack just counts as one villager so the population is far under the requisite for golem spawning.  Can you do anything about that?

**Comment by mrcoffee1026** [comment]
Well that would be cool.  Is there an option or is it automatic that they do not stack mobs that have been nametaged?

**Comment by mrcoffee1026** [comment]
If i feed a stack of 25 cows, I instantly acquire a stack of 25 offspring.  While this is super convenient and OP, I sort of doubt that was the intended behavior (should only be able to produce a stack of offspring half the size of the original stack).

**Comment by Nathat23** [comment]
To prevent stacking in a region, you can use the 'entity-stacking' worldgiard flag.

**Comment by Nathat23** [comment]
Does this still persist? If so, please create a new issue for each problem you have so it can be easily managed.
