### ISSUE TITLE
slime not split when die

### ISSUE THREAD

**Issue by comonier** [Nathat23/StackMob-2#5]
the mob-spawner slimes are no longer spliting, by dying regardless of the size they were fading

**Comment by comonier** [comment]
https://jd.bukkit.org/org/bukkit/event/entity/SlimeSplitEvent.html
did u have some problem on https://jd.bukkit.org/org/bukkit/event/entity/SlimeSplitEvent.html in plugin ?
cause i didnt found any option on config to enable / disable it

**Comment by Nathat23** [comment]
The multiplication of slimes using the SlimeSplitEvent is included in StackMob 2.1 and can be disabled in the config.
