### ISSUE TITLE
Question: Cache file / latest changes (-1)

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-2#55]
Hey there.
Running StackMob-2 compiled as of your latest commits.

I am noticing a lot of -1 entries in your cache file:
Example of my most recent:
https://gist.githubusercontent.com/andrewkm/6b07414b63ee4340fba9be5c36fe8354/raw/c91c5253b5d543d1d14bce8ccc6e77fca4983dd0/gistfile1.txt

Any thing you can let me know in regards to why this is happening / perhaps a way to safely purge / clean the file. It's already at 19,214 lines which is quite huge. I can only imagine how big this will get weeks down the road.

**Comment by Nathat23** [comment]
You see -1 entries because they are entities, that are eligible for stacking, but have not been stacked yet.

**Comment by andrewkm** [comment]
Ah, interesting, that explains it. Thank you!
