### ISSUE TITLE
Villager stacking issues.

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-2#56]
Villager stacking is a major problem for us.
Even though they follow profession when stacking each profession offers different trades.

As well, due to the stacking, I'm seeing villagers that have a cleric title but are buying raw meats. Or villagers having the nitwit tag but are actually buying stuff.

Other examples include: A tool smith that buys wool (like a shepherd) but also buys iron and sells tools. He was the last villager in a small stack (the others were killed in lava).

**Comment by Nathat23** [comment]
I can't do anything about specific trades, however I may be able to group villagers more specifically.

**Comment by andrewkm** [comment]
Grouping more specifically would be awesome!

**Comment by andrewkm** [comment]
@Nathat23 I've had some users do some testing and these are the results we are getting:
https://www.ecocitycraft.com/forum/threads/villager-type-misnamed.176344/#post-984658

Please see the two bottom posts by **Gluupor**

Here is a screenshot of both if it is easier:
Post: https://i.imgur.com/93PaThx.png

**Comment by Nathat23** [comment]
Gluupor was on the right track. The problem was that the version id was being set for 1.12 instead of 1.12.2, since they contain 1.12, which is checked for before 1.12.2 is checked.

**Comment by andrewkm** [comment]
Awesome, will load this onto production during our next maintenance period and hopefully have some more results soon :)

**Comment by andrewkm** [comment]
@Nathat23 good stuff man, thanks a lot!
Latest tests show good results according to the players :)
https://www.ecocitycraft.com/forum/threads/villager-type-misnamed.176344/
