### ISSUE TITLE
Error Code

### ISSUE THREAD

**Issue by MysticCity** [Nathat23/StackMob-2#6]
17.11.2017 13:40:44 [SEVERE] Could not pass event EntityDeathEvent to StackMob v2.1.1
17.11.2017 13:40:44 org.bukkit.event.EventException: null
17.11.2017 13:40:44 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
17.11.2017 13:40:44 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
17.11.2017 13:40:44 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
17.11.2017 13:40:44 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
17.11.2017 13:40:44 	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:394) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
17.11.2017 13:40:44 	at net.minecraft.server.v1_12_R1.EntityLiving.die(EntityLiving.java:1109) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
17.11.2017 13:40:44 	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:951) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
17.11.2017 13:40:44 	at net.minecraft.server.v1_12_R1.EntityHuman.attack(EntityHuman.java:1030) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
17.11.2017 13:40:44 	at net.minecraft.server.v1_12_R1.EntityPlayer.attack(EntityPlayer.java:1302) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
17.11.2017 13:40:44 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1616) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
17.11.2017 13:40:44 	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:69) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
17.11.2017 13:40:45 	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
17.11.2017 13:40:45 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
17.11.2017 13:40:45 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
17.11.2017 13:40:45 	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
17.11.2017 13:40:45 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
17.11.2017 13:40:45 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
17.11.2017 13:40:45 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
17.11.2017 13:40:45 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
17.11.2017 13:40:45 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
17.11.2017 13:40:45 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
17.11.2017 13:40:45 Caused by: java.lang.IllegalArgumentException: bound must be greater than origin
17.11.2017 13:40:45 	at java.util.concurrent.ThreadLocalRandom.nextInt(Unknown Source) ~[?:1.8.0_144]
17.11.2017 13:40:45 	at uk.antiperson.stackmob.events.entity.Death.onDeath(Death.java:64) ~[?:?]
17.11.2017 13:40:45 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
17.11.2017 13:40:45 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
17.11.2017 13:40:45 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
17.11.2017 13:40:45 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
17.11.2017 13:40:45 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
17.11.2017 13:40:45 	... 20 more

Stacked Mobs are killes all and not one by one
and drops only one and not multi
same with dmg

**Comment by Nathat23** [comment]
Disable kill-step in your config.

**Comment by MysticCity** [comment]
THX but dosnt work for animals

**Comment by Nathat23** [comment]
Could you explain further?

**Comment by MysticCity** [comment]
Animals like Pig... chicken with #xName
Died all with 1 hit not hone by one like the zombies or spiders

**Comment by Nathat23** [comment]
Does it do the same thing when you spawn in new ones?

**Comment by MysticCity** [comment]
ahhhhh okay thx 

sorry to waste your time
