### ISSUE TITLE
"Remove duplicate code" has broken "kill-step"

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-2#60]
Hello.
Your latest commit here: https://github.com/Nathat23/StackMob-2/commit/195efe4340071166397251f2a802f029abc54da0

Has completely broken kill-step.
Building upon previous commits all works fine. Tested and confirmed.

**Comment by JamieSinn** [comment]
You changed the logic.
https://github.com/Nathat23/StackMob-2/commit/195efe4340071166397251f2a802f029abc54da0#diff-cffe3129114c8bb7a86d2eb07bb3814bR53

No longer works because of the logic condition.

**Comment by Nathat23** [comment]
Works fine for me.
Do you have 'kill-all' enabled as well as 'kill-step' in your config?

**Comment by andrewkm** [comment]
@Nathat23 yes, we have kill-all enabled for FALL only.
Following is the config we are using:
https://gist.githubusercontent.com/andrewkm/5c816581ec207e9933408a6be2aaf418/raw/e6aab64ac4813d7780fe63873ee5292b3740f9dc/gistfile1.txt

Once again, reverting your latest commit fixes your issue entirely for us.
Let me know if you require any other information.

**Comment by andrewkm** [comment]
Thank you @Nathat23 :) Confirming this is now tested and fixed in https://github.com/Nathat23/StackMob-2/commit/5461006a5aa32c0d785b39dd7ff626fc4ee599cf
