### ISSUE TITLE
Not receiving all the exp from kill-all/kill-step.

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-2#61]
Any help with this would be greatly appreciated.

My configuration file can be seen below:
https://pastebin.com/raw/ssKaBjWM

kill-all/kill-step is enabled with specific whitelists, as well the following option is true:
_multiply-exp-enabled: true_

We have recently received the following bug report:

**Brief Description:**
killing >1 mobs from a stack only yields exp for the first and a fraction for every other mob killed

**Instructions:**
have a stack of mobs (for the ease of testing i recommend blaze as they yield exactly 10exp per mob)
kill >1
see how you only get 10 for the first mob a fraction of exp for every additional mob killed

**How many times did you recreate this?:**
couple times, one time i took the following screenshots

**Result:**
gained 12 exp after killing 4 blazes

**Expected Result:**
gain 40 exp as supposed to (referring to the test i made the screenshots with)
or whatever scaling the plugin config had before the update of the plugin (i know that kill-step in the config was messed up as well after updating)

**Evidence:**

i made sure the spawner was actually not spawning to avoid having faulty results due to restacking.

**amount in stack before:**
https://i.imgur.com/G4T0tBH.png

**amount of exp before:**
https://i.imgur.com/RBLow5r.png

**amount in stack after:**
https://i.imgur.com/8Dyr2Ox.png

**amount of exp after:**
https://i.imgur.com/RP4xbqq.png

@gluupor if you have anything to add please let us know :)

**Comment by Gluupor** [comment]
it looks like with the 
https://github.com/Nathat23/StackMob-2/commit/195efe4340071166397251f2a802f029abc54da0#diff-cffe3129114c8bb7a86d2eb07bb3814bR53

the calculation for the experience drop was changed. instead of setting the exp the entity is supposed to drop, it spawns in experience orbs as it seems either that or the fact that the calculation itself seems to differ quite a bit (imo) i guess is the cause of the faulty exp drops

**Comment by andrewkm** [comment]
Reeeeeee
That commit causing trouble :P

**Comment by JamieSinn** [comment]
https://github.com/Nathat23/StackMob-2/commit/195efe4340071166397251f2a802f029abc54da0#diff-cffe3129114c8bb7a86d2eb07bb3814bR91 

You added a config check.

**Comment by Gluupor** [comment]
oh yea im not used to github yet this much ... what jamie tagged (and the changes made a couple lines above) is actually what i was referring to im sorry

**Comment by Gluupor** [comment]
i might be seeing things or misunderstanding how its supposed to work but on
#diff-cffe3129114c8bb7a86d2eb07bb3814bL49
and
#diff-cffe3129114c8bb7a86d2eb07bb3814bL74

you were doing "subtractamount - 1" respectively "oldsize - 1" to calculate the exp
and passing "subtractamount - 1" / "oldsize - 1" to calculate the drops within "multiplication(...)"

with the change
you are actually still passing "subtractamount - 1" / "oldsize - 1" when calling "multiplication(...)"
but also doing "subtractamount - 1" again when calculating the exp within multiplication(...)
#diff-cffe3129114c8bb7a86d2eb07bb3814bR92

so if i am not mistaken you actually subtract 2 when calculating the exp as opposed to subtract 1 before the change.

**Comment by Gluupor** [comment]
the changes made just went live on the server and i did the following test:

before:
https://i.imgur.com/i2tVChv

killed 4; expected 40exp got 27:
https://imgur.com/svinnhn

killed another 3; expected 30exp got 19:
https://imgur.com/MYdJzXG

still not getting the amount of exp the amount of mobs would actually give. a blaze gives 10 so a multiple kill would /should give exp accordingly... its not really fixed unless theres a secret scaling that i am not aware of.

**Comment by andrewkm** [comment]
@Nathat23 let us know if you have any ideas on how to get this working as it did prior to the duplicate code commit.
