### ISSUE TITLE
a killstack of 1 doesnt work and still kills the whole stack

### ISSUE THREAD

**Issue by TheSenseiNL** [Nathat23/StackMob-2#7]
Hi, i got the following issue:

i want people to be able to kill stacked mobs 1 at a time. Every setting here works, except if i set it to 1.
When i set it to 1 and you kill a mob, still the whole stack dies....

(see the botom line of my pastebin)
https://pastebin.com/ry8k5YJ3

**Comment by Nathat23** [comment]
disable kill-step and kill-all, then the stack will decrease by 1 when killed
