### ISSUE TITLE
Potentially improved villager stacking.

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-2#74]
I wanted to bring an issue regarding villagers (_once again, I know lol_) and stacking them.
These are the kind of reports we are still getting regarding villagers
_(of course we can just disable villager stacking, but having it work properly would be optimal)_:

> I only noticed this recently since we got a villy spawner, and beforehand my team was mostly using villagers we bred before stacking was implemented.
> 
> When villagers stack, it will sometimes remove trades. For example, Clerics (purple) are supposed to have these trades:
> 
> https://imgur.com/a/edQpeWG
> 
> All clerics have these trades, the only difference is the amount at which you can trade. This range is included in the screenshot. Upon unstacking five or so clerics, however, the first tier of trades (zombie flesh/gold) was missing, and it had skipped to the second tier.
> 
> Since I'm pretty sure this isn't intended, here we are. This does indirectly nerf villagers by taking away some of their usefulness, but once you have a villager breeder up it doesn't matter as much.
> 
> Upon more testing, I'm pretty sure I figured out what's happening (album below):
>https://imgur.com/a/DtWz0Op
> 
> This stack still had the tier one trades for clerics. Upon killing one of the stack the tier one trades vanished. I also tested this on Blacksmiths and Librarians with the same result. Killing more of the stack afterwards does not erase any more tiers.
> 
> I'll be doing more testing and updating this bug report if I find any new bugs with stacking and villagers.
> 
> 
> UPDATE:
> 
> So it turns out splitting the villagers also messes up the trades, meaning that only the first one split will ever have the tier one trades. This is really bad - it means that once a stack is created it 'erases' all the tier one trades from every villager in the stack except for the first one split off.
> 
> On our island we had a few clerics that were unstacked and had all trades beforehand. Somehow they stacked (they were unnamed but seperated) and when I split one off the stack had the first tier of trades erased, same as above when I killed one of the stack.

It would be nice if villager stacking would work just a little more in depth.

PS: I'd like to seriously thank you for your recent work with StackMobs, it means a lot to have so many of these issues fixed up :)

**Comment by andrewkm** [comment]
I have updated the above quotation with the latest edits on our bug/report.
Original report can be found here: https://www.ecocitycraft.com/forum/threads/villager-stacking-messing-up-trades.176967/

**Comment by Nathat23** [comment]
Since this happens when a new entity is spawned I'm guessing there is something wrong with the duplication - not sure what though.

**Comment by Nathat23** [comment]
This might be a bug in spigot's villager api as this can be easily replicated with only one plugin.

**Comment by Nathat23** [comment]
Closed because this has been fixed.
