### ISSUE TITLE
coloring for sheep

### ISSUE THREAD

**Issue by HeroModek** [Nathat23/StackMob-2#77]
**Describe the bug**
When I change the color of a sheep that has been stacked it is unpacked, is this error? Is it supported?

**Comment by HeroModek** [comment]
When I change the color of a sheep that has been stacked it is unpacked, is this error? Is it supported?

**Comment by Nathat23** [comment]
That is intentional.

**Comment by Nathat23** [comment]
Closing because of no further response.
