### ISSUE TITLE
Mythicmob

### ISSUE THREAD

**Issue by WindUnwaken** [Nathat23/StackMob-2#80]
**Describe the bug**
https://hastebin.com/kikumumuce.vbs

**Bukkit/Spigot AND StackMob version:**
Spigot 1.12.2 StackMob 2.2.12 mythicmob 4.4.0

**Comment by Nathat23** [comment]
Are you using the latest mythicmobs?

**Comment by Nathat23** [comment]
I can't replicate.
Can you provide more information about what you were doing at the time, the mobs involved etc?

**Comment by Nathat23** [comment]
Please respond or this will be closed.
I also can't really replicate because I do not have access to the premium versions of MythicMobs - works fine on 4.3.2.

**Comment by Nathat23** [comment]
Closed due to no response.
