### ISSUE TITLE
Bug /w nametag 

### ISSUE THREAD

**Issue by Frostyeiz** [Nathat23/StackMob-2#82]
_Sorry If my sentences are weird to understand because English isn't my native language._

I don't have much thing to said, all have been capped into this video below:
**(You only need watch the first 7-9 seconds of the video, the remains aren't necessary at all)**
[https://www.youtube.com/watch?v=8pXGtvy9J90](https://www.youtube.com/watch?v=8pXGtvy9J90])

In term of words: If you use a nametag on some mob, the stack will be duplicate. Although the original stack (in the video) decreased from 10x to 9x, the (duplicated) stack is the 10x, it behavior seems to be normal.
The original stack has it drop normal. (I have 'kill-all' and 'multiply-drop' turned on)
The duplicated stack (10x) only drops as same as a normal (pig), only drop 1-3 raw parkchop

I'm using PaperClip 916.2 for 1.10(.2) version, Stackmob 2.2.12 SNAPSHOT (this bug also works on other older versions)

**Comment by andrewkm** [comment]
@Nathat23 as per our player testing, it would seem this issue can be considered fixed.
https://ecocitycraft.com/forum/threads/breeding-name-tag-bug-possible-duplication-glitch.177130/
