### ISSUE TITLE
Breeding / name tag bug / possible duplication glitch

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-2#83]
Original report here:
https://www.ecocitycraft.com/forum/threads/breeding-name-tag-bug-possible-duplication-glitch.177130/

In depth test stated as such:

> Cows have a chance of dropping 0-2 leather and 0-3 raw beef.
> This means that killing 10 cows will give between 0-20 leather and 0-30 raw beef.
> 
> Killing cows individually:
> 7 leather
> 24 raw beef
> 
> Killing cows after splitting each from the reported bug above:
> 10 leather
> 18 raw beef
> 
> The behavior I saw in-game didn't really reflect any sort of duplication glitch. The cow would split and assume the name of the stack, but that would be it. It simply had the name, but did not behave like a stack. As for the "actual" stack, it would decrease by 1, meaning that the cow that split was properly accounted for.
> 
> What is buggy behavior, however, is that not only does the cow split from the stack and assume the name from the stack it was originally in (in this case, a cow that split from a "10x Cow" stack would be named "10x Cow" and the stack would change to become "9x Cow") but also the name tag isn't consumed, it just stays in your inventory.
> 
> Please note, the above tests were done with a Name Tag that hadn't been named yet (It was still called "Name Tag"). When I used a named Name Tag, none of this behavior occurred and the Name Tag worked as intended (consumed, properly named and split from the stack).

Using latest StackMob built upon this commit:
https://github.com/Nathat23/StackMob-2/commit/2b796529769ca02fda683f7793e81bd54323b9a5
Config: https://pastebin.com/raw/9vDEMFMS

**Comment by Nathat23** [comment]
Related to #82 ?

**Comment by JamieSinn** [comment]
They seem to be the same yes.

**Comment by andrewkm** [comment]
@Nathat23 as per our player testing, it would seem this issue can be considered fixed.
https://ecocitycraft.com/forum/threads/breeding-name-tag-bug-possible-duplication-glitch.177130/
