### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by CoolPanda101** [Nathat23/StackMob-2#89]
Hey I was using your stack mob plugin with the custom mob drops made by aminecraftdev and they both work perfectly almost - I found out that your plugin makes each mob drop natural loot and there was no option in config to turn it of because the custom mob drops the natural mob drops are off and I have put custom mob drops on but stil drops natural mob drops by your plugin I even got aminecraftdev to add a debug to his plugin which it worked fine

**Comment by Nathat23** [comment]
See my response to your PM on spigot.
