### ISSUE TITLE
Chicken Egg Server Crash

### ISSUE THREAD

**Issue by Spazzinq** [Nathat23/StackMob-2#9]
https://gist.github.com/Spazzinq/251ab677481e6add27afdc573a26784d

Error that is thrown when it crashes ^

TacoSpigot 1.8.8
Latest StackMob (2.1.2)

**Comment by Nathat23** [comment]
Is there more to it than that?

**Comment by Spazzinq** [comment]
Not really, I have no knowledge of being near chickens.

**Comment by Nathat23** [comment]
You don't need to be near chickens, the chunks just need to be loaded.

**Comment by Spazzinq** [comment]
Anotha one if it's helpful: https://gist.github.com/Spazzinq/959ee5e54aed8e4edfaccb3dd6a8e53e

**Comment by iaxedu** [comment]
Same issue

https://hastebin.com/surehevido.vbs
https://hastebin.com/ekijepoged.md

**Comment by Nathat23** [comment]
I've changed the drop location a bit, maybe it will help?

**Comment by Spazzinq** [comment]
OOF https://gist.github.com/Spazzinq/ef3328bc9ebce883c7bd4607054e010d

**Comment by Nathat23** [comment]
Hmm, okay then. As a temporary fix disable 'chicken-eggs' under the 'multiply' section.

**Comment by Tarka-Dhal** [comment]
StackOverflowError - Somewhere is recursive loop.

**Comment by mustul** [comment]
Hi Nathat,

This issue is caused by spawning an item in ItemSpawnEvent so ItemSpawnEvent -> ItemSpawn - > ItemSpawnEvent and so on.

You can fix this issue by adding some kind of modifier to the itemstack in  function dropDrops in file DropTools.java and check presence of this modifier in ItemDropEvent in file ItemDrop.java and when this modifier is present return the event function so it will not get cycled. 

Have a nice day! :)

**Comment by Nathat23** [comment]
@mustul I did do that before with metadata but it didn't make any difference. I'm guessing the itemspawnevent was fired before I set the metadata?

**Comment by Nathat23** [comment]
Thinking about it, I could probably do this using a delayed task.

**Comment by mustul** [comment]
Yes, the event is called inside the dropNaturally function that is the reason i said modifier to itemstack not item entity so it will be already available in the item spawn event. I personally fixed it with adding unsafe enchant to the item as a special modifier and checking and removing this enchant in the item spawn event and it works just fine.

**Comment by mustul** [comment]
And no the task is not solusion because it will just cause to stack more and more tasks in the task queue and eventualy cause out of memory error and of course wrong number of spawned items.

**Comment by mustul** [comment]
Ehm sorry for a lot of comments :D but I just got a better idea. You can set global boolean variable before spawning all of the items and check the state of this variable in the spawn event so it will not get executed. I hope this is the last comment for now :D good luck fixing the problem. Choose whichever option you want :)

**Comment by Nathat23** [comment]
Updating to v2.2.2 should fix this problem.

**Comment by Nathat23** [comment]
I'd thought I'll keep this open if there are any issues
