### ISSUE TITLE
 Guardian Some loot unleashed bug

### ISSUE THREAD

**Issue by AsheEcho** [Nathat23/StackMob-2#91]
**Describe the bug**
monster giving two or more loot items like a guardian.
The first spoils of prison marine sculptures are plunder,
The second and third spoils of prison marinade and fish are not plundered

**To Reproduce**
If there are more than two aunt, damage will be pickled.

**Expected behavior**
Get more Guardian to get a sea lantern

**Screenshots/Videos**
![2018-07-29 11 21 06_0](https://user-images.githubusercontent.com/41845460/43362391-e6e1af46-9323-11e8-9fe1-7c7cc308e730.png)

As shown in the picture
, Plucking is applied to sculptures, but crystals and fish are not applied.

**Bukkit/Spigot AND StackMob version:**

1.12.2/1.12.2/2.2.14

**Additional context**

Because of this bug, We have to kill more Guardian to make a sea lantern.

**Comment by Nathat23** [comment]
so basically the sea lanterns are not being multiplied?

**Comment by AsheEcho** [comment]
Without looting but crystals and fish appear similar
But the sculpture is subject to looting
Does not overlap due to mobstack
All Trophies Apply of looting

**Comment by Nathat23** [comment]
add 'SEA_LANTERN' to the 'multiply-drops.whitelist'  list in the config,this will be added by default in 2.4.
