### ISSUE TITLE
Duplication Bug

### ISSUE THREAD

**Issue by bartyrealms** [Nathat23/StackMob-2#92]
**Describe the bug**
Zombies in a mob stack are able to pick up items, and when killed with looting swords, the stack will drop more than what was given to the zombie.

**To Reproduce**
Create zombie stack. Turn setting to multiply drops based on number of mobs in the stack. Drop gold bar to zombie. Kill zombie with looting 3 sword. Get tons of items in return.

**Expected behavior**
It should drop what was given to him, not more.

**Bukkit/Spigot AND StackMob version:**
StackMob-2.2.14-SNAPSHOT
Spigot most recent 1.12.2

**Comment by Nathat23** [comment]
Fixed.
