### ISSUE TITLE
1.13

### ISSUE THREAD

**Issue by Yukyxy** [Nathat23/StackMob-2#93]
Hi In 1.13 I have this error
https://pastebin.com/3smWB2wH

**Comment by Nathat23** [comment]
What version of worldguard are you using?

**Comment by Yukyxy** [comment]
Here => https://www.spigotmc.org/wiki/spigot-1-13-plugin-compatibility-list/

http://builds.enginehub.org/job/worldguard?branch=string-ids

**Comment by Nathat23** [comment]
Looks like the API has changed.
