### ISSUE TITLE
New feature request.

### ISSUE THREAD

**Issue by BourneDev** [Nathat23/StackMob-2#94]
I was wondering if you could add a way to stack mobs by their name. So if they have a custom name set with setCustomName(String name), I would love something to be added so that it separates these mobs into their own stack. 

So if it has no name, it would be the way it is now, but then if it has a name it would be %mobName% followed by the name of a normal stacked mob.

Basically, to keep it simple, I would like a feature to stack mobs by name.

Can this be added please? Thank you very much!

**Comment by Nathat23** [comment]
What is the purpose of this?

**Comment by BourneDev** [comment]
We have "upgraded mobs" on our server and they get turned into normal mobs and put into normal stacks. We would love it if we could separate them by their name so their name is not taken away.

**Comment by Nathat23** [comment]
With 3.0, there is a class that this can be done with. Make a class that implements ApplicableTrait, then register it with TraitManager#registerTrait when the server enables.
