### ISSUE TITLE
mythicmobs false no work

### ISSUE THREAD

**Issue by p82183645** [Nathat23/StackMob-2#95]
i set

mythicmobs:
    # If Mythicmobs should stack together
    enabled: false
    # MythicMob types that shouldn't stack, use the 'internal name'
    blacklist:
       - ''

but Mythicmobs will still stack
this bug

use paper 1.12.2

**Comment by p82183645** [comment]
What do you mean?
i test set , false and true
Will be superimposed

How do I close it?

**Comment by Nathat23** [comment]
This is an issue with the wording. To disable stacking you will have to wait for 2.4 so you can use the 'ALL' option in the blacklist.
