### ISSUE TITLE
Damage issue

### ISSUE THREAD

**Issue by CyrusMusic101** [Nathat23/StackMob-2#98]
**Describe the bug**
For me when mobs stack like for instance 50 zombies and they hit me it counts as if all of them where hitting me instead of one

**To Reproduce**
Just install the plugin

**Expected behavior**
to only take damage as if it was one hitting me.

**Screenshots/Videos**

**Bukkit/Spigot AND StackMob version:**
Self explanatory.

**Additional context**
Nope

**Comment by Nathat23** [comment]
That is intended behavior, set "multiply-damage-done" to false to disable it.
